The testMe() function exits if string s is equal to 'reset'
and when state is equal to 9. state can only reach 9
when char c has been equal to these values: [({ ax})]. c gets its
values from inputChar(), so inputChar() had to return the ASCII
values from Space to ~. The random char c is generated by getting
a random int value from 32 to 126 and converting it to its equivalent
char character. The random string s is created by randomly selecting a char
in the same manner as inputChar(), but the range is limited to the lower-case
alphabet characters a-z (ASCII values 97-122). A char array of size 6 is built
consisting of 5 random chars and a NULL terminator. 
